### ISSUE TITLE
Deprecation notice: v1, v2, and v3 of the artifact actions

### ISSUE THREAD

**Issue by gusgonnet** [particle-iot/compile-action#31]
Hey, I can observe this warning:

![image](https://github.com/user-attachments/assets/42411e69-de57-42cf-abe6-be9c162461a5)

In text:
[Deprecation notice: v1, v2, and v3 of the artifact actions](https://github.com/gusgonnet/solar-pressure-sensor/actions/runs/11605170466/workflow)
The following artifacts were uploaded using a version of actions/upload-artifact that is scheduled for deprecation: "firmware-artifact".
Please update your workflow to use v4 of the artifact actions.
Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

Anything we should be worried about?
Thanks

**Comment by laupow** [comment]
@gusgonnet that screenshot shows a need to update the [`actions/upload-artifact`](https://github.com/actions/upload-artifact) version in your workflow.

No major concerns—it’s normal for Actions workflows to need occasional updates.

Most `actions/` tools rarely make breaking changes, so you can usually bump to v4 without issues.

#26 tracks a similar upgrade and related notice for the `compile-action`, so I'm going close this issue
